spring.application.name=LojaCarro

# URL do Banco de Dados com criação automática
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/jhonata?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURAÇÃO CORRIGIDA: Força o uso do dialeto moderno (InnoDB/UTF8)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Encoding UTF-8
spring.jpa.properties.hibernate.connection.charSet=UTF-8