PS C:\Users\20241148060039\Downloads\Testing_acticons_car_store> git commit -m "atualizado o sonar"
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
PS C:\Users\20241148060039\Downloads\Testing_acticons_car_store> git branch -M main
PS C:\Users\20241148060039\Downloads\Testing_acticons_car_store> git add .
PS C:\Users\20241148060039\Downloads\Testing_acticons_car_store> git commit -m "atualizado o sonar"
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
PS C:\Users\20241148060039\Downloads\Testing_acticons_car_store>  
